SET IDENTITY_INSERT [dbo].[Sandwiches] ON
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (21, N'BLT', CAST(0.400 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (22, N'BBQ Pulled Pork', CAST(0.420 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (23, N'Sub', CAST(0.665 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (24, N'Reuben', CAST(0.788 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (25, N'PB & J', CAST(0.340 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (26, N'Grilled Cheese', CAST(0.390 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (27, N'Egg Salad', CAST(0.012 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (28, N'Cucumber Sandwiches', CAST(0.467 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (29, N'Chicken Salad', CAST(0.344 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (30, N'Hoagie', CAST(0.232 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (31, N'Grinder', CAST(0.690 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (32, N'Fluffernutter', CAST(0.766 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (33, N'Kentucky Hot Brown', CAST(0.602 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (34, N'Italian BMT', CAST(0.878 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (35, N'Tuna Melt', CAST(0.871 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (36, N'Turkey, Bacon, Avacodo (TBA)', CAST(0.912 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (37, N'Monte Cristo', CAST(0.964 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (38, N'Sloppy Joe', CAST(0.984 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (39, N'Cuban', CAST(0.789 AS Decimal(18, 3)))
INSERT INTO [dbo].[Sandwiches] ([Id], [SandwichName], [SandwichModifier]) VALUES (40, N'Ham and Cheese', CAST(0.884 AS Decimal(18, 3)))
SET IDENTITY_INSERT [dbo].[Sandwiches] OFF
